the_grocer/expenses/urls.py
from django.urls import path
from .views import (IndexView, 
                    ItemCreate, 
                    success, 
                    ItemDetail,
                    ItemUpdate,
                    ItemDelete)

app_name = "expenses"

urlpatterns = [
    path('index/',  IndexView.as_view(), name='index'),
    path('new/', ItemCreate.as_view(), name='create'),
    path('success/', success, name='success'),
    path('detail/<int:pk>/', ItemDetail.as_view(), name='detail'),
    path('update/<int:pk>/', ItemUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ItemDelete.as_view(), name='delete')
]

the_grocer/the_grocer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('expenses/',  include('expenses.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

the_grocer/expenses/models.py
from django.db import models
from django.utils import timezone

class Item(models.Model):
    title = models.CharField(max_length=30, default="Item Title")
    TYPE_CHOICES = (
        ('Transportation', 'Transportation'),
        ('Food', 'Food'),
        ('Alcohol', 'Alcohol'),
        ('Cigarettes', 'Cigarettes'),
        ('Electronics', 'Electronics'),
        ('Leisure', 'Leisure'),
        ('Travelling', 'Travelling')
        )
    type = models.CharField(max_length=14, choices=TYPE_CHOICES, default="Transportation")
    amount = models.FloatField()
    location = models.CharField(max_length=30, default="Locale")
    image = models.FileField(upload_to='uploads/')
    comments = models.TextField(default='Thoughts...')
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "- " + self.title

the_grocer/expenses/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import (
                                ListView, 
                                DetailView, 
                                UpdateView,
                                DeleteView)
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .models import Item


class IndexView(ListView):
    template_name = 'expenses/index.html'

    def get_queryset(self):
        return Item.objects.all()

class ItemCreate(CreateView):
    model = Item
    fields = ['title', 'type', 'amount', 'location', 'image', 'comments', 'date']
    success_url = "/expenses/success/"

class ItemUpdate(UpdateView):
    model = Item
    fields = ['title', 'type', 'amount', 'location', 'image', 'comments', 'date']
    success_url = "/expenses/success/"

def success(request):
    return HttpResponse("<h2>Success!</h2><br><a href='/expenses/index/'><button type='button'>Go back to Index</button></a>")

class ItemDetail(DetailView):
    model = Item
    template_name = 'expenses/detail.html'

class ItemDelete(DeleteView):
    model = Item
    success_url = reverse_lazy('expenses:index')

the_grocer/expenses/templates/expenses/detail.html
{% if object %}
    <ul>
        <li>ID: {{object.id}}</li>
        <li>Title: {{object.title}}</li>
        <li>Type: {{object.type}}</li>
        <li>Amount: {{object.amount}}</li>
        <li>Location: {{object.location}}</li>
        <li>Comments: {{object.comments}}</li>
        <li>Date Posted: {{ object.date | date:"F d, Y" }}</li>
    </ul>
    <a href="{% url 'expenses:update' object.pk %}"><button type="button">Edit</button></a>
    <a href="{% url 'expenses:delete' object.pk %}"><button type="button">Delete</button></a>
{% endif %}

the_grocer/expenses/templates/expenses/index.html
{% if object_list %}
    <ul>
        {% for object in object_list %}
            <li>
                <a href="{% url 'expenses:detail' object.pk %}">{{ object.title }}</a>
            </li>
        {% endfor %}
        <br>
        <a href="{% url 'expenses:create' %}"><button type="button">New</button></a>
    </ul>
{% else %}
    <h2>No files at the moment, why don't you add one?</h2>
{% endif %}

the_grocer/expenses/templates/expenses/item_confirm_delete.html
<form action="" method="post">{% csrf_token%}
    <p>Delete "{{ object.title }}" ?</p>
    <input type="submit" value="Confirm" />
</form>

the_grocer/expenses/templates/expenses/item_form.html
<fieldset>
    <legend>Create an Item</legend>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}{{ form.as_p }}
            <input type="submit" name="Submit" value="Submit">
        </form>
</fieldset>
    